before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: NLTCxIkMKjgVl4Zfs72MdK5BOvznuLbKizaGV7Kc8gCbaIZwTMNDiYOj/7cCydoCUJZFn034BgxiM0+0cvS3raxGJ/VleAiONsOuYqursffIMUC9PG3lVxS+8uaY34gTgKG9pMtf+YO419OkDSF1UMu+bDKC320TrmQNjsaFSAAoXfDcgbH3VuvjWRg99nxgpGvPZRR/sv+r0EYOijPaRlpaQJJ6mHdlTrzfuvogUcrYHkTxMcaLZ/KcxFBIFt3bpCWKzirRk6uUfW1Ca342wEFYyjMjba3eUgLQHlHUxsqpCn4BXloE/o7KJWJFB8pIY05xfeq4QgNR9mRnlVAM90pFDebs9szvAnUCkRqZW03riFAw+VBGtYMHhVvRQYnm5wE3i7isgEiE7IbNjTyLp7bq97lGle9G2Li4Mm63iLnYN3TfPLU8ot5/f1UNQGIReHBGWUW6HO8GXeYjA0sirre80uOLjGt9pe5zFQ5gE5MsRszl2IAFX+HfSI7FvGSW3cKtxh6AmZAob07SC8beo6VDmvSNg0TBvFwho0vFyN9cbOvAZaGtAyjZ+0cDYggwB+Nz3MwpQyHbBGlOnynVjpb61nU6cT4VhgCTDd4du5HuH8xTi6Tz7y79KMXLEwhVbJnfd1fimOY7noYEtbEt8jvwQxlnVf9AngoReSb7Pq0= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
